### ISSUE TITLE
error occurs when install but ok with terminal

### ISSUE THREAD

**Issue by junqi-lu** [kailous/CDecrypt-for-mac#1]
Chip Apple M1
macOS Ventura 13.0.1

double click "CDerypt for mac" and double click Setup.app. It shows:
"Setup.app" is damaged and can't be opened. You should eject the disk image. 

But I success with following the terminal way.

**Comment by kailous** [comment]
This is a problem with application signing. You can use the manual command line provided in the readme.md to install and run. app just runs the shell with shortcuts.app.

**Comment by junqi-lu** [comment]
> This is a problem with application signing. You can use the manual command line provided in the readme.md to install and run. app just runs the shell with shortcuts.app.

get it. Command line work. Thanks for ur work
